-- Insert data into Employees
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aditi Khanna', 'Analyst', 'Jaipur', '1-2', 'Y', 653874, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pooja Kaur', 'Senior Analyst', 'Banglore', '2-3', 'Y', 798703, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kajal Mehta', 'Analyst', 'Banglore', '1-2', 'Y', 663851, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amaya Joshi', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bilal Kulkarni', 'Associate', 'Jaipur', '3-4', 'Y', 976125, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Girish Reddy', 'Analyst', 'Pune', '1-2', 'Y', 670531, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Esha Dhillon', 'Analyst', 'Pune', '1-2', 'Y', 652076, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kashi Nair', 'Analyst', 'Banglore', '1-2', 'Y', 655787, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Himanshu Dhillon', 'Senior Analyst', 'Pune', '2-3', 'Y', 895396, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hetal Bhatia', 'Senior Analyst', 'Pune', '2-3', 'Y', 820895, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anusha Verma', 'Analyst', 'Jaipur', '1-2', 'Y', 693712, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mukta Iyer', 'Analyst', 'Banglore', '1-2', 'Y', 680229, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hari Menon', 'Analyst', 'Pune', '0-1', 'N', 570000, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jai Menon', 'Senior Associate', 'Pune', '6-7', 'Y', 1704253, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kalpana Sharma', 'Analyst', 'Banglore', '1-2', 'Y', 669692, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Leena Verma', 'Analyst', 'Banglore', '1-2', 'Y', 677168, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arvind Sinha', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 734868, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anshul Gupta', 'Analyst', 'Jaipur', '1-2', 'Y', 667001, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Devi Menon', 'Senir Associate', 'Jaipur', '1-2', 'Y', 1714061.2500000002, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Farhan Gupta', 'Analyst', 'Pune', NULL, 'Y', 665610, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajeshwari Joshi', 'Associate', 'Banglore', '3-4', 'Y', 1180331, 'No');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Damodar Kumar', 'Associate', 'Jaipur', '4-5', 'Y', 910994, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Om Sinha', 'Senior Analyst', 'Banglore', '2-3', 'Y', 846412, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kunal Kaur', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nishant Reddy', 'Senior Analyst', 'Banglore', '2-3', 'N', 750000, '2024-05-15 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gowri Iyer', 'Analyst', 'Pune', '1-2', 'Y', 696236, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akshita Verma', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Renu Gupta', 'Senior Associate', 'Banglore', '5-6', 'Y', 2291090, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mira Verma', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chhavi Mehta', 'Associate', 'Jaipur', '4-5', 'Y', 1032250, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manasi Kulkarni', 'Analyst', 'Banglore', '1-2', 'Y', 673339, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kiran Banerjee', 'Analyst', 'Banglore', '1-2', 'N', 699114, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Farah Mehta', 'Analyst', 'Pune', '0-1', 'N', 570000, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kala Gupta', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aayush Verma', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akanksha Mehta', 'Analyst', 'Jaipur', '1-2', 'Y', 695543, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lohit Reddy', 'Analyst', 'Banglore', '1-2', 'Y', 683759, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jayesh Chowdhury', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-05-14 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nirmala Verma', 'Senior Analyst', 'Banglore', '2-3', 'Y', 839893, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Alka Reddy', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Praveen Joshi', 'Senior Analyst', 'Banglore', '2-3', 'Y', 839782, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anisha Chowdhury', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, 'No');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prema Khanna', 'Associate', 'Banglore', '3-4', 'Y', 1254653, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pritha Sinha', 'Associate', 'Banglore', '4-5', 'Y', 1336002, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Karthika Joshi', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-05-17 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kalyani Patel', 'Analyst', 'Banglore', '0-1', 'N', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bindiya Pillai', 'Associate', 'Jaipur', '4-5', 'Y', 1098051, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Annapurna Mehta', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Niraj Kumar', 'Senior Analyst', 'Banglore', '2-3', 'N', 747748, '2024-06-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nila Patel', 'Senior Analyst', 'Banglore', '2-3', 'Y', 748140, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bhanu Kapoor', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 842482, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Deepali Joshi', 'Senir Associate', 'Jaipur', NULL, 'Y', 1324501.875, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Poornima Mehta', 'Senior Analyst', 'Banglore', '2-3', 'Y', 738224, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manju Kaur', 'Analyst', 'Banglore', '1-2', 'Y', 663969, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajesh Kapoor', 'Associate', 'Banglore', '4-5', 'Y', 1264754, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kamala Kumar', 'Analyst', 'Banglore', '1-2', 'Y', 669187, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Reena Dhillon', 'Senior Associate', 'Banglore', '5-6', 'Y', 2452003, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gayathri Kumar', 'Analyst', 'Pune', '0-1', 'N', 570000, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Archana Reddy', 'Analyst', 'Jaipur', '1-2', 'Y', 656199, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Devang Iyer', 'Senir Associate', 'Jaipur', NULL, 'Y', 1869885, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rati Rao', 'Senior Associate', 'Banglore', '5-6', 'Y', 1915774, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bala Verma', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 787635, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Atul Bhatia', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 764485, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Astha Banerjee', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 810920, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hima Kaur', 'Senior Analyst', 'Pune', '2-3', 'Y', 823326, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aarya Reddy', 'Analyst', 'Jaipur', '1-2', 'Y', 668855, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ravi Bhatia', 'Senior Associate', 'Banglore', '6-7', 'Y', 2007027, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jyoti Kaur', 'Analyst', 'Banglore', '0-1', 'Y', 570000, 'No');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Namrata Kulkarni', 'Analyst', 'Banglore', '1-2', 'Y', 694768, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abhilasha Kapoor', 'Analyst', 'Jaipur', '1-2', 'Y', 658651, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anmol Dhillon', 'Analyst', 'Jaipur', '1-2', 'Y', 682058, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ajit Dhillon', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nishita Kapoor', 'Senior Analyst', 'Banglore', '2-3', 'N', 812000, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nitesh Nair', 'Senior Analyst', 'Banglore', '2-3', 'Y', 806381, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arun Iyer', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 813200, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arjun Joshi', 'Senior Analyst', 'Jaipur', '1-2', 'Y', 723808, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nitya Menon', 'Senior Analyst', 'Banglore', '1-2', 'Y', 789598, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Indira Kumar', 'Associate', 'Pune', '3-4', 'Y', 907115, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hrithik Gupta', 'Senior Analyst', 'Pune', '1-2', 'Y', 886891, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nalini Sinha', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chandni Kaur', 'Associate', 'Jaipur', '2-3', 'N', 964851, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Avinash Dhillon', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 765357, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Inderjit Patel', 'Associate', 'Pune', '2-3', 'Y', 991402, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rani Khanna', 'Manager', 'Banglore', '8-9', 'Y', 3079338, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akash Gupta', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anuj Sharma', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Punit Bhatia', 'Associate', 'Banglore', '4-5', 'N', 1093366, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mehul Kumar', 'Analyst', 'Banglore', '1-2', 'Y', 679372, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pratyush Kapoor', 'Senior Analyst', 'Banglore', '2-3', 'Y', 882835, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Harshita Chowdhury', 'Senior Analyst', 'Pune', '2-3', 'Y', 844734, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bhoomi Menon', 'Associate', 'Jaipur', '2-3', 'Y', 974829, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manish Chowdhury', 'Analyst', 'Banglore', '1-2', 'Y', 666771, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lata Sharma', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Madhuri Nair', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Poonam Dhillon', 'Senior Analyst', 'Banglore', '2-3', 'N', 780000, 'July 1, 2024');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anita Banerjee', 'Analyst', 'Jaipur', '1-2', 'Y', 674629, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prem Menon', 'Associate', 'Banglore', '2-3', 'Y', 1161030, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ranjeet Kulkarni', 'Senior Associate', 'Banglore', '4-5', 'Y', 1744115, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chinmay Gupta', 'Associate', 'Jaipur', '3-4', 'Y', 968562, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rahul Kumar', 'Associate', 'Banglore', '4-5', 'Y', 1107472, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abhijeet Nair', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chandan Bhatia', 'Associate', 'Jaipur', '4-5', 'Y', 1096816, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hiral Mehta', 'Senior Analyst', 'Pune', '2-3', 'N', 747378, '2024-06-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Barkha Reddy', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 784515, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Radhika Sharma', 'Associate', 'Banglore', '4-5', 'Y', 1038994, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akhil Sharma', 'Analyst', 'Jaipur', '1-2', 'Y', 661872, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ketan Pillai', 'Analyst', 'Banglore', '1-2', 'N', 689119, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Harini Khanna', 'Analyst', 'Pune', '1-2', 'Y', 679122, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jagadish Nair', 'Senior Associate', 'Pune', '4-5', 'Y', 2119272, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mohini Joshi', 'Analyst', 'Banglore', '1-2', 'Y', 675832, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akshay Kumar', 'Analyst', 'Jaipur', '1-2', 'Y', 677326, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Isha Singh', 'Associate', 'Pune', '3-4', 'Y', 999847, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abhay Singh', 'Analyst', 'Jaipur', '1-2', 'Y', 667696, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Naina Khanna', 'Analyst', 'Banglore', '1-2', 'Y', 657556, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anil Pillai', 'Analyst', 'Jaipur', '1-2', 'Y', 666688, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Neeraj Dhillon', 'Senior Analyst', 'Banglore', '2-3', 'Y', 827191, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lochana Singh', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Meena Sharma', 'Analyst', 'Banglore', '1-2', 'Y', 650999, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nanda Pillai', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manisha Banerjee', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Diya Rao', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kirti Rao', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Malati Khanna', 'Analyst', 'Banglore', '1-2', 'Y', 689746, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kavya Menon', 'Analyst', 'Banglore', '1-2', 'N', 652764, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Agni Chowdhury', 'Analyst', 'Jaipur', '1-2', 'Y', 668447, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Damini Verma', 'Manager', 'Jaipur', '7-8', 'Y', 2910548, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amitabh Menon', 'Analyst', 'Jaipur', '1-2', 'Y', 695121, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ishita Joshi', 'Associate', 'Pune', '4-5', 'Y', 990176, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Drishti Bhatia', 'Analyst', 'Pune', '1-2', 'Y', 665297, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jayant Kulkarni', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mayank Gupta', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rakesh Menon', 'Manager', 'Banglore', '9-10', 'Y', 3287201, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Raj Verma', 'Associate', 'Banglore', '3-4', 'Y', 1479593, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gita Kapoor', 'Analyst', 'Pune', '0-1', 'N', 570000, '2024-06-25 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pratibha Verma', 'Senior Analyst', 'Banglore', '1-2', 'Y', 866178, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jitendra Bhatia', 'Analyst', 'Banglore', '1-2', 'Y', 693467, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Balraj Singh', 'Senior Analyst', 'Jaipur', '2-3', 'N', 739278, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Dhaval Pillai', 'Analyst', 'Pune', '1-2', 'Y', 688026, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Leela Kumar', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ahana Banerjee', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mitra Singh', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manav Pillai', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ashok Chowdhury', 'Senior Analyst', 'Jaipur', '1-2', 'Y', 831898, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anjali Rao', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anand Sinha', 'Analyst', 'Jaipur', '1-2', 'Y', 675379, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kamini Singh', 'Analyst', 'Banglore', '1-2', 'Y', 671736, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pallavi Pillai', 'Senior Analyst', 'Banglore', '2-3', 'Y', 823585, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kushan Dhillon', 'Analyst', 'Banglore', '1-2', 'Y', 699616, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mahendra Iyer', 'Analyst', 'Banglore', '1-2', 'Y', 693026, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajat Reddy', 'Associate', 'Banglore', '3-4', 'Y', 1580928, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jigar Rao', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nikita Sharma', 'Senior Analyst', 'Banglore', '2-3', 'N', 800000, '2024-06-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Azad Kumar', 'Senior Analyst', 'Jaipur', '1-2', 'Y', 874157, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hema Banerjee', 'Senior Analyst', 'Pune', '2-3', 'Y', 837838, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Dhanya Kulkarni', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ranjana Sinha', 'Manager', 'Banglore', '9-10', 'Y', 2586435, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ayush Patel', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 860479, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mohan Kapoor', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mukesh Nair', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chitrangada Patel', 'Associate', 'Jaipur', '3-4', 'Y', 1023034, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Durga Kaur', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Megha Patel', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ayesha Sharma', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 797979, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arnav Nair', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 759937, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gopal Nair', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Priyanka Chowdhury', 'Associate', 'Banglore', '3-4', 'Y', 1370487, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Divya Banerjee', 'Analyst', 'Pune', '1-2', 'Y', 694789, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Purva Dhillon', 'Associate', 'Banglore', '3-4', 'Y', 1022523, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bipin Chowdhury', 'Associate', 'Jaipur', '3-4', 'Y', 950310, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Dhruv Chowdhury', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prabhakar Gupta', 'Senior Analyst', 'Banglore', '2-3', 'Y', 878914, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Neha Mehta', 'Senior Analyst', 'Banglore', '2-3', 'Y', 803203, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajani Singh', 'Associate', 'Banglore', '4-5', 'Y', 1550000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prajwal Kumar', 'Senior Analyst', 'Banglore', '2-3', 'Y', 798506, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rashmi Chowdhury', 'Senior Associate', 'Banglore', '6-7', 'Y', 2415447, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gitanjali Joshi', 'Analyst', 'Pune', '1-2', 'Y', 662617, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manjari Rao', 'Analyst', 'Banglore', '1-2', 'Y', 685966, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Parvati Rao', 'Senior Analyst', 'Banglore', '2-3', 'Y', 766540, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aanya Sharma', 'Analyst', 'Jaipur', '1-2', 'Y', 684097, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Haritha Kulkarni', 'Senior Analyst', 'Pune', '2-3', 'Y', 874620, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pratik Singh', 'Senior Analyst', 'Banglore', '2-3', 'Y', 894749, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mansi Dhillon', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abishek Menon', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lalit Gupta', 'Analyst', 'Banglore', '1-2', 'Y', 688925, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nutan Khanna', 'Senior Analyst', 'Banglore', '2-3', 'N', 757860, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arushi Khanna', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 731274, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ravindra Kaur', 'Senior Associate', 'Banglore', '4-5', 'Y', 2084629, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amrita Khanna', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Neela Bhatia', 'Senior Analyst', 'Banglore', '2-3', 'Y', 781187, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajni Iyer', 'Associate', 'Banglore', '4-5', 'N', 1100000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rajiv Nair', 'Associate', 'Banglore', '4-5', 'Y', 1364647, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ratan Banerjee', 'Senior Associate', 'Banglore', '4-5', 'Y', 2078123, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ishani Kapoor', 'Associate', 'Pune', '3-4', 'Y', 1011693, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Keshav Sinha', 'Analyst', 'Banglore', '1-2', 'N', 660441, '2024-05-17 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Priti Kulkarni', 'Associate', 'Banglore', '3-4', 'Y', 1171667, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Karan Reddy', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bhavin Joshi', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 800808, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ashish Pillai', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 808913, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ankita Kaur', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Naresh Rao', 'Analyst', 'Banglore', '1-2', 'Y', 669647, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Raghu Patel', 'Associate', 'Banglore', '3-4', 'Y', 1279950, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gayatri Verma', 'Analyst', 'Pune', '1-2', 'Y', 667714, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Indrani Verma', 'Associate', 'Pune', '4-5', 'N', 1100000, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rhea Sharma', 'Senior Associate', 'Banglore', '6-7', 'Y', 1884348, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anurag Kumar', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Atharv Rao', 'Senior Analyst', 'Jaipur', '2-3', 'N', 850060, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rachana Gupta', 'Associate', 'Banglore', '3-4', 'N', 1150000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Alok Singh', 'Analyst', 'Jaipur', '1-2', 'Y', 679088, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ishaan Reddy', 'Associate', 'Pune', '4-5', 'Y', 901372, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Harsha Pillai', 'Senior Analyst', 'Pune', '2-3', 'N', 743907, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Deepa Reddy', 'Senir Associate', 'Jaipur', NULL, 'Y', 1324501.875, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Priya Pillai', 'Associate', 'Banglore', '4-5', 'Y', 1423630, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nitin Iyer', 'Senior Analyst', 'Banglore', '2-3', 'Y', 822884, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lakshmi Mehta', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prutha Banerjee', 'Associate', 'Banglore', '4-5', 'Y', 1130975, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kamal Verma', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Madhav Kapoor', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ankit Bhatia', 'Analyst', 'Jaipur', '1-2', 'Y', 682722, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bijay Khanna', 'Associate', 'Jaipur', '3-4', 'Y', 958924, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kshitij Bhatia', 'Analyst', 'Banglore', '1-2', 'Y', 698795, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nandini Chowdhury', 'Analyst', 'Banglore', '1-2', 'Y', 673115, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ayaan Gupta', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 874505, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pratima Reddy', 'Senior Analyst', 'Banglore', '2-3', 'N', 757280, '2024-05-12 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pankaj Chowdhury', 'Senior Analyst', 'Banglore', '2-3', 'Y', 885800, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Madhu Joshi', 'Analyst', 'Banglore', '1-2', 'Y', 681109, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mahima Menon', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Deepika Nair', 'Senir Associate', 'Jaipur', NULL, 'Y', 1542655.125, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amit Nair', 'Analyst', 'Jaipur', '1-2', 'Y', 669794, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Geetanjali Singh', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Puneet Rao', 'Associate', 'Banglore', '3-4', 'Y', 1502831, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kedar Khanna', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bhavna Nair', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 881213, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mukul Menon', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bikram Sinha', 'Associate', 'Jaipur', '4-5', 'Y', 1020947, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amita Iyer', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Amar Kapoor', 'Analyst', 'Jaipur', '1-2', 'Y', 687204, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aishwarya Rao', 'Analyst', 'Jaipur', '1-2', 'Y', 696134, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Bhavya Iyer', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 807821, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ajeet Kaur', 'Analyst', 'Jaipur', '1-2', 'Y', 652519, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kavita Iyer', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Preity Iyer', 'Senior Analyst', 'Banglore', '1-2', 'Y', 749271, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Avni Mehta', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 813458, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abhiram Iyer', 'Analyst', 'Jaipur', '1-2', 'Y', 695357, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Narain Banerjee', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-07-01 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Asha Kulkarni', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 808047, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Deepak Kapoor', 'Senir Associate', 'Jaipur', NULL, 'Y', 1714061.2500000002, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Abhinav Joshi', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Advaita Kulkarni', 'Analyst', 'Jaipur', '1-2', 'Y', 694539, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ananya Kulkarni', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Hemant Rao', 'Senior Analyst', 'Pune', '2-3', 'Y', 732142, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chetan Dhillon', 'Associate', 'Jaipur', '3-4', 'Y', 917419, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Dhairya Khanna', 'Senir Associate', 'Jaipur', NULL, 'Y', 1402413.75, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pavan Bhatia', 'Senior Analyst', 'Banglore', '2-3', 'N', 865555, '2024-05-17 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Areen Kapoor', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Kabir Dhillon', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-05-17 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Parul Banerjee', 'Senior Analyst', 'Banglore', '2-3', 'Y', 753470, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ila Sharma', 'Senior Analyst', 'Pune', '2-3', 'Y', 805979, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manjeet Bhatia', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aakash Patel', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rekha Mehta', 'Senior Associate', 'Banglore', '6-7', 'Y', 2121197, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Prachi Sharma', 'Senior Analyst', 'Banglore', '2-3', 'Y', 816659, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Rashi Pillai', 'Senior Associate', 'Banglore', '5-6', 'Y', 2295146, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aditya Sinha', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Avani Kaur', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 813559, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Padma Kulkarni', 'Senior Analyst', 'Banglore', '2-3', 'Y', 879923, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aarav Gupta', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Harish Sinha', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Karthik Kapoor', 'Analyst', 'Banglore', '1-2', 'Y', 660243, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Maruti Mehta', 'Analyst', 'Banglore', '1-2', 'Y', 693416, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Fathima Sharma', 'Analyst', 'Pune', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nitara Joshi', 'Senior Analyst', 'Banglore', '2-3', 'Y', 754564, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nikhil Gupta', 'Senior Analyst', 'Banglore', '2-3', 'Y', 856722, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Darshan Singh', 'Manager', 'Jaipur', '8-9', 'Y', 3039209, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Purab Kaur', 'Associate', 'Banglore', '2-3', 'Y', 1137127, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jaya Sinha', 'Analyst', 'Banglore', '1-2', 'Y', 657432, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jayanti Pillai', 'Analyst', 'Banglore', '1-2', 'Y', 672615, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Gautam Patel', 'Analyst', 'Pune', '1-2', 'Y', 686097, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Manas Sinha', 'Analyst', 'Banglore', '0-1', 'N', 570000, '2024-05-17 00:00:00');
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Lavanya Patel', 'Analyst', 'Banglore', '1-2', 'Y', 659554, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Brinda Banerjee', 'Associate', 'Jaipur', '4-5', 'Y', 1019658, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Arundhati Menon', 'Senior Analyst', 'Jaipur', '2-3', 'Y', 841886, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Advika Pillai', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Akshara Patel', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Anuradha Patel', 'Analyst', 'Jaipur', '1-2', 'Y', 654800, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chaitanya Rao', 'Associate', 'Jaipur', '3-4', 'Y', 1031403, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Nisha Singh', 'Senior Analyst', 'Banglore', '2-3', 'Y', 842589, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Neelam Kaur', 'Senior Analyst', 'Banglore', '2-3', 'Y', 771600, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jhanvi Banerjee', 'Analyst', 'Banglore', '1-2', 'Y', 689961, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Aravind Singh', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jaidev Khanna', 'Manager', 'Pune', '8-9', 'Y', 2945176, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Chirag Sharma', 'Associate', 'Jaipur', '4-5', 'Y', 1007064, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Dhanush Sinha', 'Senir Associate', 'Jaipur', NULL, 'Y', 1402413.75, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Mitali Reddy', 'Analyst', 'Banglore', '1-2', 'Y', 664724, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ketaki Kulkarni', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Jahnavi Iyer', 'Senior Associate', 'Pune', '5-6', 'Y', 1729701, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pradnya Patel', 'Senior Analyst', 'Banglore', '2-3', 'Y', 882632, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Khushi Chowdhury', 'Analyst', 'Banglore', '0-1', 'Y', 570000, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Preethi Nair', 'Senior Analyst', 'Banglore', '2-3', 'Y', 828900, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Pushpa Mehta', 'Associate', 'Banglore', '4-5', 'Y', 1030381, NULL);
INSERT INTO Employees (Name, Role, Location, Experience, IsActive, CurrentCompensation, LastWorkingDay) VALUES ('Ajay Bhatia', 'Analyst', 'Jaipur', '0-1', 'Y', 570000, NULL);

-- Insert data into IndustryCompensation
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Jaipur', 'Manager', 2337356.25);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Jaipur', 'Senior Associate', 1558237.5);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Jaipur', 'Associate', 1038825);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Jaipur', 'Senior Analyst', 769500);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Jaipur', 'Analyst', 570000);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Pune', 'Manager', 2583393.75);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Pune', 'Senior Associate', 1722262.5);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Pune', 'Associate', 1148175);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Pune', 'Senior Analyst', 850500);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Pune', 'Analyst', 630000);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Banglore', 'Manager', 2706412.5);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Banglore', 'Senior Associate', 1804275.0000000002);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Banglore', 'Associate', 1202850);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Banglore', 'Senior Analyst', 891000.0000000001);
INSERT INTO IndustryCompensation (Location, Role, AverageCompensation) VALUES ('Banglore', 'Analyst', 660000);

-- Insert data into EmployeeRatings
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (1, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (2, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (3, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (4, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (5, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (6, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (7, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (8, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (9, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (10, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (11, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (12, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (13, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (14, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (15, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (16, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (17, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (18, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (19, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (20, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (21, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (22, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (23, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (24, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (25, 4.5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (26, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (27, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (28, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (29, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (30, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (31, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (32, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (33, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (34, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (35, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (36, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (37, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (38, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (39, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (40, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (41, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (42, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (43, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (44, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (45, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (46, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (47, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (48, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (49, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (50, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (51, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (52, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (53, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (54, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (55, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (56, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (57, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (58, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (59, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (60, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (61, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (62, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (63, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (64, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (65, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (66, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (67, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (68, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (69, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (70, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (71, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (72, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (73, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (74, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (75, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (76, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (77, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (78, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (79, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (80, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (81, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (82, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (83, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (84, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (85, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (86, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (87, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (88, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (89, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (90, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (91, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (92, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (93, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (94, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (95, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (96, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (97, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (98, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (99, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (100, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (101, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (102, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (103, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (104, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (105, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (106, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (107, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (108, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (109, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (110, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (111, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (112, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (113, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (114, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (115, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (116, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (117, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (118, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (119, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (120, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (121, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (122, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (123, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (124, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (125, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (126, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (127, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (128, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (129, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (130, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (131, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (132, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (133, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (134, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (135, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (136, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (137, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (138, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (139, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (140, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (141, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (142, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (143, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (144, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (145, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (146, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (147, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (148, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (149, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (150, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (151, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (152, 5, 3.5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (153, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (154, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (155, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (156, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (157, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (158, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (159, 5, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (160, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (161, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (162, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (163, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (164, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (165, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (166, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (167, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (168, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (169, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (170, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (171, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (172, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (173, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (174, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (175, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (176, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (177, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (178, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (179, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (180, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (181, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (182, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (183, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (184, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (185, 5, 3.5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (186, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (187, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (188, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (189, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (190, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (191, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (192, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (193, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (194, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (195, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (196, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (197, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (198, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (199, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (200, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (201, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (202, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (203, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (204, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (205, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (206, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (207, 5, 2);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (208, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (209, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (210, 5, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (211, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (212, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (213, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (214, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (215, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (216, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (217, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (218, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (219, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (220, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (221, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (222, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (223, 5, 3.5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (224, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (225, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (226, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (227, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (228, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (229, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (230, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (231, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (232, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (233, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (234, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (235, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (236, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (237, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (238, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (239, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (240, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (241, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (242, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (243, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (244, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (245, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (246, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (247, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (248, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (249, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (250, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (251, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (252, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (253, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (254, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (255, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (256, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (257, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (258, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (259, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (260, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (261, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (262, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (263, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (264, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (265, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (266, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (267, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (268, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (269, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (270, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (271, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (272, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (273, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (274, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (275, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (276, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (277, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (278, 4, 3);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (279, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (280, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (281, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (282, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (283, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (284, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (285, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (286, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (287, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (288, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (289, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (290, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (291, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (292, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (293, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (294, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (295, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (296, 5, 5);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (297, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (298, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (299, 4, 4);
INSERT INTO EmployeeRatings (EmpID, SelfRating, ManagerRating) VALUES (300, 5, 5);